name: faux-unittest

on:
  pull_request:
    branches: [ master ]
    paths:
      - LICENSE
      - '**.md'
      - .github/workflows/run-crucible-tracking.yaml
      - .github/workflows/faux-unittest.yaml
      - .github/workflows/faux-crucible-ci.yaml
      - 'docs/**'
      - engine/engine-script-library.py
      - engine/engine-script.py

jobs:
  unittest-complete:
    runs-on: ubuntu-latest
    steps:
    - name: Confirm Success
      run: echo "faux-unittest-complete"
