name: unittest

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - LICENSE
      - '**.md'
      - '.github/rulesets/**'
      - .github/workflows/run-crucible-tracking.yaml
      - .github/workflows/crucible-merged.yaml
      - .github/workflows/faux-unittest.yaml
      - .github/workflows/faux-crucible-ci.yaml
      - 'docs/**'
      - engine/engine-script-library.py
      - engine/engine-script.py
      - 'userenvs/rhel-ai-*.json'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/unittest
  cancel-in-progress: true

jobs:
  blockbreaker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd util
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pytest pytest-html jsonschema

      - name: Run unit tests
        run: |
          cd util
          source .venv/bin/activate
          pytest -v --html=report.html --self-contained-html blockbreaker.py validate_run_file.py tests/*.py

      - name: Upload html report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: util/report.html

  unittest-complete:
    runs-on: ubuntu-latest
    needs:
    - blockbreaker
    steps:
    - name: Confirm Success
      run: echo "unittest-complete"
